INSERT INTO Customer (FirstName, LastName, Address, IsDeleted) VALUES
(N'Juan', N'Pérez', N'Av. Pellegrini 1200, Rosario', 0),
(N'Ana', N'Gómez', N'Bv. Oroño 850, Rosario', 0),
(N'Lucas', N'Fernández', N'Córdoba 1450, Rosario', 0),
(N'María', N'López', N'San Martín 2300, Rosario', 0),
(N'Carlos', N'Rodríguez', N'Mendoza 980, Rosario', 0),
(N'Lucía', N'Martínez', N'Italia 400, Rosario', 0),
(N'Jorge', N'Díaz', N'Av. Alberdi 2100, Rosario', 0),
(N'Camila', N'Ruiz', N'Catamarca 700, Rosario', 0),
(N'Martín', N'Sosa', N'Entre Ríos 1600, Rosario', 0),
(N'Valentina', N'Torres', N'Av. Francia 1100, Rosario', 0),
(N'Pablo', N'Castro', N'Rioja 500, Rosario', 0),
(N'Florencia', N'Molina', N'Av. Belgrano 300, Rosario', 0),
(N'Diego', N'Acosta', N'Buenos Aires 1900, Rosario', 0),
(N'Natalia', N'Romero', N'Zeballos 1400, Rosario', 0),
(N'Sebastián', N'Herrera', N'Urquiza 600, Rosario', 0),
(N'Carolina', N'Navarro', N'Montevideo 900, Rosario', 0),
(N'Federico', N'Ramos', N'Av. Eva Perón 4800, Rosario', 0),
(N'Agustina', N'Vera', N'Gálvez 1300, Rosario', 0),
(N'Andrés', N'Benítez', N'Paraguay 1700, Rosario', 0),
(N'Melina', N'Flores', N'Av. San Martín 3200, Rosario', 0),
(N'Gonzalo', N'Méndez', N'Callao 1000, Rosario', 0),
(N'Paula', N'Ibarra', N'Av. Wheelwright 200, Rosario', 0),
(N'Ignacio', N'Peralta', N'Brown 1800, Rosario', 0),
(N'Julieta', N'Rinaldi', N'Av. Provincias Unidas 900, Rosario', 0),
(N'Tomás', N'Quiroga', N'Laplace 1400, Rosario', 0);
