INSERT INTO car VALUES
(null, 'SUV', 'Toyota', 'RAV4', 0),
(NULL, 'Sedan', 'Toyota', 'Corolla', 0),
(NULL, 'Pickup 4x4', 'Toyota', 'Hilux', 0),
(NULL, 'SUV', 'Ford', 'Explorer', 0),
(NULL, 'Pickup 4x4', 'Ford', 'Ranger', 0),
(NULL, 'Sedan', 'Ford', 'Focus', 0),
(NULL, 'SUV', 'Chevrolet', 'Tracker', 0),
(NULL, 'Sedan', 'Chevrolet', 'Cruze', 0),
(NULL, 'Pickup 4x4', 'Chevrolet', 'S10', 0),
(NULL, 'SUV', 'Volkswagen', 'Tiguan', 0),
(NULL, 'Sedan', 'Volkswagen', 'Vento', 0),
(NULL, 'Hatchback', 'Volkswagen', 'Golf', 0),
(NULL, 'SUV', 'Honda', 'CR-V', 0),
(NULL, 'Sedan', 'Honda', 'Civic', 0),
(NULL, 'Sedan', 'Honda', 'Accord', 0),
(NULL, 'SUV', 'Nissan', 'X-Trail', 0),
(NULL, 'Sedan', 'Nissan', 'Sentra', 0),
(NULL, 'Pickup 4x4', 'Nissan', 'Frontier', 0),
(NULL, 'SUV', 'Jeep', 'Compass', 0),
(NULL, 'SUV 4x4', 'Jeep', 'Wrangler', 0),
(NULL, 'SUV', 'Hyundai', 'Tucson', 0),
(NULL, 'Sedan', 'Hyundai', 'Elantra', 0),
(NULL, 'SUV', 'Kia', 'Sportage', 0),
(NULL, 'Sedan', 'Kia', 'Cerato', 0),
(NULL, 'Sedan', 'BMW', 'Serie 3', 0);
